import Link from "next/link";
import Image from "next/image";
import Breadcrumbs from "@/components/Breadcrumbs";
import ProductStructuredData from "@/components/ProductStructuredData";
import SearchProductConfigurator from "@/components/configurator/SearchProductConfigurator";
import { SEARCH_PRODUCTS, searchProductPath, searchProductPrice, searchProductDefaults, type SearchProduct } from "@/lib/searchProductDefinitions";
import { formatMoneyDisplay } from "@/lib/pricing";
import { siteConfig } from "@/lib/siteConfig";

export default function SearchProductPage({ product }: { product: SearchProduct }) {
    const price = searchProductPrice(product), defaults = searchProductDefaults(product);
    const related = SEARCH_PRODUCTS.filter(p => p.category === product.category && p.slug !== product.slug).slice(0,4);
    const url = `${siteConfig.url}${searchProductPath(product)}`;
    return <main className="min-h-screen bg-slate-50 pb-16 pt-24 text-slate-900"><ProductStructuredData product={{ name: product.title, description: product.short, image: `${siteConfig.url}${product.image}`, sku: `model-${product.category}-${product.slug}`, brand: siteConfig.domain, offers: { price: price.total.toFixed(2), priceCurrency: "RON", availability: "https://schema.org/InStock", url } }} /><div className="mx-auto max-w-7xl px-4"><Breadcrumbs items={[{label:"Produse",href:"/produse"},{label:product.category==="rollup"?"Roll-up":product.category==="pvc-forex"?"Decoruri PVC":product.category==="afise"?"Afișe":"Autocolante și etichete",href:`/shop?category=${product.category}`},{label:product.title,href:searchProductPath(product)}]} /><div className="mt-6"><SearchProductConfigurator product={product} /></div>
        <section className="rounded-2xl border border-slate-200 bg-white p-6 sm:p-8"><h2 className="text-xl font-bold">Cum folosești acest model</h2><div className="mt-4 space-y-4 leading-relaxed text-slate-700">{product.description.split("\n\n").map((paragraph,i)=><p key={i}>{paragraph}</p>)}</div><ul className="mt-5 list-disc space-y-2 pl-5 text-sm leading-relaxed text-slate-600">{product.notes.map(note=><li key={note}>{note}</li>)}</ul></section>
        <section className="mt-8 rounded-2xl border border-slate-200 bg-white p-6 sm:p-8"><h2 className="text-xl font-bold">Întrebări despre comandă</h2><div className="mt-5 space-y-5 text-sm leading-relaxed"><div><h3 className="font-bold">Ce include prețul afișat inițial?</h3><p className="mt-1 text-slate-600">{formatMoneyDisplay(price.total)} pentru {defaults.quantity} {defaults.quantity===1?"bucată":"bucăți"}, {product.category==="afise"?`format ${defaults.size}`:`${defaults.width} × ${defaults.height} cm per piesă`}, cu materialul preselectat și grafica modelului{product.category==="pvc-forex"?", inclusiv decuparea pe contur special selectată inițial":""}. Totalul se recalculează când schimbi opțiunile; transportul se calculează separat la finalizarea comenzii.</p></div><div><h3 className="font-bold">Pot păstra grafica și schimba textul?</h3><p className="mt-1 text-slate-600">Da. Alege modelul din pasul Grafică & Personalizare și completează câmpurile pentru textele tale. Fotografia rămâne un exemplu; indicațiile se salvează în comandă.</p></div><div><h3 className="font-bold">Pot trimite propria machetă?</h3><p className="mt-1 text-slate-600">Selectează Încarc grafica mea și așteaptă confirmarea salvării fișierului. Pentru un design nou, opțiunea de grafică personalizată afișează separat taxa existentă în configurator.</p></div></div></section>
        <section className="mt-10"><h2 className="mb-5 text-xl font-bold">Alte modele de {product.category==="rollup"?"roll-up":product.category==="pvc-forex"?"decor PVC":product.category==="afise"?"afișe":"autocolante"}</h2><div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{related.map(p=><Link href={searchProductPath(p)} key={p.slug} className="overflow-hidden rounded-2xl border border-gray-200 bg-white hover:shadow-md"><div className="relative aspect-square"><Image src={p.image} alt={p.title} fill className="object-contain p-4" sizes="(max-width:1024px) 50vw,25vw" /></div><div className="p-4"><h3 className="text-sm font-bold">{p.title}</h3><p className="mt-2 text-sm text-emerald-700">{formatMoneyDisplay(searchProductPrice(p).total)} · configurația inițială</p></div></Link>)}</div></section>
    </div></main>;
}
