export const homeprintPresentationPhotos: Record<string, string> = {
  "banner": "/products/homeprint-studio/banner.webp",
  "banner-verso": "/products/homeprint-studio/banner-verso.webp",
  "mesh": "/products/homeprint-studio/mesh.webp",
  "afise": "/products/homeprint-studio/afise.webp",
  "autocolante": "/products/homeprint-studio/autocolante.webp",
  "canvas": "/products/homeprint-studio/canvas.webp",
  "tapet": "/products/homeprint-studio/tapet.webp",
  "rollup": "/products/homeprint-studio/rollup.webp",
  "window-graphics": "/products/homeprint-studio/window-graphics.webp",
  "pliante": "/products/homeprint-studio/pliante.webp",
  "flayere": "/products/homeprint-studio/flayere.webp",
  "fonduri-eu": "/products/homeprint-studio/fonduri-eu.webp",
  "plexiglass": "/products/homeprint-studio/plexiglass.webp",
  "pvc-forex": "/products/homeprint-studio/pvc-forex.webp",
  "alucobond": "/products/homeprint-studio/alucobond.webp",
  "carton": "/products/homeprint-studio/carton.webp",
  "polipropilena": "/products/homeprint-studio/polipropilena.webp",
  "tricouri": "/products/homeprint-studio/tricouri.webp",
  "hanorace": "/products/homeprint-studio/hanorace.webp",
  "sepci": "/products/homeprint-studio/sepci.webp",
  "carti-vizita": "/products/homeprint-studio/carti-vizita.webp",
  "decor-foto-copil": "/products/homeprint-studio/decor-foto-copil.webp",
  "personaj-propriu": "/products/homeprint-studio/personaj-propriu.webp",
  "semnalistica": "/products/homeprint-studio/semnalistica.webp"
};
